import track from "../assets/track.png"
import property from "../assets/property.png"
import manage from "../assets/manage.png"
import Content from "./feature_content"
import { useState } from "react"
import Generate from "../assets/generate.png"
import Organize from "../assets/organize.png"
import {
  Settings,
  House,
  FileText,
  Phone,
  MapPin,
  ListTodo,
  AtSign,
  Megaphone,
  Image as ImageIcon,
  LayoutGrid,
  Pencil,
  Database,
  Info,
  Copy,
  UserCheck,
  ChartColumn,
  ArrowUp,
  History,
} from "lucide-react"

const featureData = [
  {
  id:1,
  variant:"sale",
  buttonText:"GENERATE MORE SALES",
  label:"faster than ever",
  heading: "Generating More Sales",
  description:
 "Supercharge your real estate sales pipeline with Property CRM, designed to capture and assign leads efficiently.",
  image: Generate,
  imageLeft: true,
  items: [
  {
    id: 1,
    icon: Settings,
    title: "Work Automation",
    text:
      "Automate your business processes to let your sales team concentrate on closing and converting leads.",
  },
  {
    id: 2,
    icon: House,
    title: "Matching Properties",
    text:
      "Leads can be captured in the CRM system and immediately matched with properties according to their requirements.",
  },
  {
    id: 3,
    icon: FileText,
    title: "Property Offers",
    text:
      "Track offers and use smart filtering tools to monitor unsold properties and identify areas that need attention.",
  },
],
  },
  {
    id: 2,
    buttonText: "ORGANIZE SALE ACTIVITIES",
    variant:"activities",
    label: "TASKS & ACTIVITIES",
    heading: "Organize Your Activities & Tasks",
    description:
      "Increase efficiency with task automation, saving time and effort while maintaining a complete customer interaction record.",
    image: Organize,
    imageLeft: false,
    items: [
  {
    id: 1,
    icon: Phone,
    title: "Calls",
    text:
      "Analyse conversations with leads to improve lead conversion strategies according to client needs.",
  },
  {
    id: 2,
    icon: MapPin,
    title: "Property Viewings",
    text:
      "Assign properties to agents, schedule viewings, and record the outcome of each appointment.",
  },
  {
    id: 3,
    icon: ListTodo,
    title: "Tasks",
    text:
      "Delegate tasks to team members to improve operational efficiency and customer service.",
  },
],
  },
  {
  id: 3,
  buttonText: "TRACK SALE CAMPAIGNS",
  label: "EFFORTS LESS WORK",
  heading: "Tracking of your Campaigns",
  highlightedHeading: "& Sales Queries",
  description:
    "Simplify your marketing campaigns with CRM by automating email, text, and social media outreach.",
  image: track,
  imageLeft: true,
  variant: "campaign",
  items: [
  {
    id: 1,
    icon: AtSign,
    title: "Email & SMS",
    text:
      "View all email and SMS exchanges from the CRM without switching to separate applications.",
  },
  {
    id: 2,
    icon: Megaphone,
    title: "Campaigns",
    text:
      "Link leads to marketing campaigns to accurately calculate the revenue generated by each marketing channel.",
  },
],
},
  {
    id: 4,
    buttonText: "PROPERTY LISTING",
    
    heading: "Manage property",
    highlightedHeading: "Listing",
    description:
      "Input all of your real estate assets into Property CRM system, including property information.",
    image: property,
    imageLeft: false,
    variant:"listing",
    items: [
  {
    id: 1,
    icon: ImageIcon,
    title: "Images",
    text: "",
  },
  {
    id: 2,
    icon: LayoutGrid,
    title: "Floor Layouts",
    text: "",
  },
  {
    id: 3,
    icon: MapPin,
    title: "Geographical Info",
    text: "",
  },
  {
    id: 4,
    icon: Pencil,
    title: "Promotion Materials",
    text: "",
  },
  {
    id: 5,
    icon: Database,
    title: "Additional Data",
    text: "",
  },
],
  },
   {
    id: 5,
    buttonText: "MANAGE TEAMS",
    
    heading: "Smoothly Manage",
    highlightedHeading: "Teams",
    description: "",
    image: manage,
    imageLeft: true,
    variant:"team",
    items: [
  {
    id: 1,
    icon: Info,
    title: "Team Planning",
    text: "",
  },
  {
    id: 2,
    icon: UserCheck,
    title: "Assigning Sale Agent to Lead",
    text: "",
  },
  {
    id: 3,
    icon: Copy,
    title: "Property Assigning",
    text: "",
  },
  {
    id: 4,
    icon: ChartColumn,
    title: "Sales Team Analytics",
    text: "",
  },
  {
    id: 5,
    icon: ArrowUp,
    title: "Multi-level Reports",
    text: "",
  },
  {
    id: 6,
    icon: History,
    title: "History of Lead",
    text: "",
  },
],
  },
]

function Feature(){
    
    const [activeTab, setActiveTab] = useState(0)
    const selectedFeature=featureData[activeTab]
    return(
        <div className="mt-4 bg-white pt-6 text-center">
            <h1 className="text-4xl text-black font-bold ">CRM Property Management Features Overview</h1>
            <p className="text-black text-sm font-medium pt-8">Streamline your property business and increase your sales with the power of CRM software</p>
            <div className="flex flex-row justify-center gap-4 pt-14 font-semibold">
                {featureData.map((tab,index)=>{
                    let buttonClasses =
                    "border border-gray-200 shadow-2xl pt-2 pb-4 px-2 transition"

                    if (activeTab === index) {
                        buttonClasses += " bg-green-700 text-white"
                        } else {
                        buttonClasses += " bg-gray-100 text-green-700 hover:text-black"
                        }

                    return(
                    <button key={tab.id} className={buttonClasses}
                    onClick={()=>setActiveTab(index)}>
                        {tab.buttonText}
                    </button>
                    )
                })}

                
            </div>
            <Content feature={selectedFeature} />
        </div>

    )
}
export default Feature 